import fs from 'fs';
import path from 'path';

const TOPICS_DIR = path.join(process.cwd(), 'src/app/(topics)');
const REGISTRY_OUT = path.join(process.cwd(), 'src/content/registry.generated.ts');

function kebabCase(str: string) {
  return /^[a-z0-9-]+$/.test(str);
}

function run() {
  if (!fs.existsSync(TOPICS_DIR)) {
    fs.mkdirSync(TOPICS_DIR, { recursive: true });
  }

  const categories = fs.readdirSync(TOPICS_DIR).filter(d => {
    const stat = fs.statSync(path.join(TOPICS_DIR, d));
    return stat.isDirectory() && !d.startsWith('.');
  });

  let imports = '';
  const allTopicsData: string[] = [];
  let categoriesArray = '';
  
  const categoryIds: string[] = [];

  for (const catId of categories) {
    if (!kebabCase(catId)) {
      console.error(`${catId}: 디렉터리명은 kebab-case여야 합니다.`);
      process.exit(1);
    }
    const catPath = path.join(TOPICS_DIR, catId);
    if (!fs.existsSync(path.join(catPath, 'category.ts'))) {
      console.error(`${catId}: category.ts가 없습니다.`);
      process.exit(1);
    }

    categoryIds.push(catId);
    const catImportName = `category_${catId.replace(/-/g, '_')}`;
    imports += `import ${catImportName} from '@/app/(topics)/${catId}/category';\n`;
    
    const topics = fs.readdirSync(catPath).filter(d => {
      const stat = fs.statSync(path.join(catPath, d));
      return stat.isDirectory() && !d.startsWith('.');
    });

    const categoryTopics: string[] = [];
    const ordersInCat = new Set<number>();
    
    for (const slug of topics) {
      if (!kebabCase(slug)) {
        console.error(`${catId}/${slug}: 디렉터리명은 kebab-case여야 합니다.`);
        process.exit(1);
      }
      const topicPath = path.join(catPath, slug);
      
      const subdirs = fs.readdirSync(topicPath).filter(d => fs.statSync(path.join(topicPath, d)).isDirectory());
      if (subdirs.length > 0) {
        console.error(`${catId}/${slug}: 주제 디렉터리는 2단계까지만 지원합니다.`);
        process.exit(1);
      }
      
      const hasMeta = fs.existsSync(path.join(topicPath, 'meta.ts'));
      const hasPage = fs.existsSync(path.join(topicPath, 'page.tsx'));
      
      if (hasMeta && !hasPage) {
        console.error(`${catId}/${slug}: meta.ts는 있으나 page.tsx가 없습니다.`);
        process.exit(1);
      }
      if (hasPage && !hasMeta) {
        console.error(`${catId}/${slug}: page.tsx에 대응하는 meta.ts가 없습니다.`);
        process.exit(1);
      }
      
      if (hasMeta && hasPage) {
        const metaContent = fs.readFileSync(path.join(topicPath, 'meta.ts'), 'utf8');
        const orderMatch = metaContent.match(/order:\s*(\d+)/);
        if (orderMatch) {
           const order = parseInt(orderMatch[1], 10);
           if (ordersInCat.has(order)) {
              console.warn(`${catId}/${slug}: 같은 카테고리 안에 order 중복 발견 (${order}). slug 사전순으로 정렬됩니다.`);
           }
           ordersInCat.add(order);
        }

        const topicImportName = `meta_${catId.replace(/-/g, '_')}_${slug.replace(/-/g, '_')}`;
        imports += `import ${topicImportName} from '@/app/(topics)/${catId}/${slug}/meta';\n`;
        
        categoryTopics.push(topicImportName);
        allTopicsData.push(`  { ...${topicImportName}, status: ${topicImportName}.status ?? 'published', slug: '${slug}', categoryId: '${catId}', href: '/${catId}/${slug}' }`);
      }
    }
    
    categoriesArray += `  { ...${catImportName}, id: '${catId}', href: '/${catId}', topics: allTopics.filter(t => t.categoryId === '${catId}' && t.status === 'published').sort((a,b) => a.order !== b.order ? a.order - b.order : a.slug.localeCompare(b.slug)) },\n`;
  }
  
  const categoryIdType = categoryIds.length > 0 ? categoryIds.map(c => `'${c}'`).join(' | ') : 'string';
  
  const out = `// AUTO-GENERATED by scripts/generate-topic-registry.mts — DO NOT EDIT.
import type { CategoryEntry, TopicEntry } from './types';

${imports}
export type CategoryId = ${categoryIdType};

export const allTopics: TopicEntry[] = [
${allTopicsData.join(',\n')}
];

export const allCategories: CategoryEntry[] = [
${categoriesArray}
];
allCategories.sort((a,b) => a.order - b.order);
`;

  fs.mkdirSync(path.dirname(REGISTRY_OUT), { recursive: true });
  fs.writeFileSync(REGISTRY_OUT, out, 'utf-8');
}

run();
